Repository usc-cisco/hermes-api, pull requests merged in 2025-01, with the labels that each got.

#2 feat: setup devx tooling
  .github/pull_request_template.md
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .lintstagedrc.js
  bun.lockb
  commitlint.config.js
  eslint.config.mjs
  package.json
  vitest.config.mts
Labels: enhancement

#20 feat(coordinator): add controllers to update status, fetch course info + status
  src/db/services/coordinator.service.ts
  src/db/services/queue-number.service.ts
  src/index.ts
  src/models/CourseUnion.ts
  src/models/StatusUnion.ts
  src/routers/coordinator.router.ts
  src/routers/queue.router.ts
  src/types/abstracts/coordinator-service.abstract.ts
  src/types/abstracts/queue-number-service.abstract.ts
  src/types/entities/Coordinator.ts
  src/types/entities/Course.ts
  src/types/entities/QueueNumber.ts
  src/types/entities/dtos/CourseUnion.ts
  src/types/entities/dtos/StatusUnion.ts
Labels: enhancement

#21 feat: add logger, rate limiter, cors middleware, improve logger util
  bun.lockb
  package.json
  src/config/env.config.ts
  src/index.ts
  src/utils/logger.util.ts
Labels: enhancement

#26 fix(logging): use pino-pretty stream instead of transport
  src/index.ts
  src/utils/logger.util.ts
Labels: bug

#23 feat(router): create queue router
  src/db/models/queue-number.model.ts
  src/db/services/queue-number.service.ts
  src/db/utils/seed.ts
  src/routers/queue.router.ts
  src/types/abstracts/queue-number-service.abstract.ts
  src/types/entities/QueueNumber.ts
Labels: enhancement

#41 feat: add email property & improve docs
  package.json
  src/db/models/coordinator.model.ts
  src/db/utils/seed.ts
  src/index.ts
  src/types/entities/Coordinator.ts
Labels: bug, enhancement

#44 fix: explicitly state cors allowed methods
  src/index.ts
Labels: bug

#47 fix: make all global error handlers return the proper HTTP status code
  src/index.ts
  src/routers/coordinator.router.ts
Labels: bug
